audio_tokenizer:
  _target_: sparkvox.tools.tokenizer.audio_tokenizer.bicodec.audio_tokenizer.BiCodecTokenizer
  #config_path: "egs/codec/bicodec/results/bicodec.24k/20250420_014312/config.yaml"
  config_path: "egs/codec/bicodec/config/bicodec.24k.yaml"
  #ckpt_path: "egs/codec/bicodec/results/bicodec.24k/20250420_014312/ckpt/epoch=0010_step=110000.ckpt"
  ckpt_path: "pretrained_models/Spark-TTS-0.5B/BiCodec/model.safetensors"
  #wav2vec_model: "/aifs4su/xinshengwang/model/wav2vec2-large-xlsr-53"
  wav2vec_model: "pretrained_models/wav2vec2-large-xlsr-53"